spring:
  application:
    name: backend
  datasource:
#    url: jdbc:postgresql://ep-still-sunset-a53rpn5q-pooler.us-east-2.aws.neon.tech/croplog_base
#    username: neondb_owner
#    password: npg_HZVaiL8Js5Am
    url: postgresql://postgres:ciB55-net@db.alitamacelzglkdfuojd.supabase.co:5432/postgres
    username: postgres
    password: ciB55-net
    properties:
      sslmode: require
#    username: root
#    password: ciB55-net
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#        to enable and optimize batch processing (next 3 settings)
        jdbc:
          order_inserts: true
          order_updates: true
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 25

    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
     init:
      mode: never

#  security.oauth2:
#    resourceserver:
#      jwt:
#        jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
#
#
#keycloak:
#  realm: master
#  auth-server-url: http://localhost:8080
#  resource: 8181
#  credentials.secret: OI4VL6uvBNoVQijsXrUrwhuh7C4mmdnC
#  bearer-only: true

# do with .env




server:
  port: 8181

